export const PAIRS_FETCH_REQUESTED = "PAIRS_FETCH_REQUESTED";
export type PAIRS_FETCH_REQUESTED = typeof PAIRS_FETCH_REQUESTED;

export const PAIRS_FETCH_SUCCEEDED = "PAIRS_FETCH_SUCCEEDED";
export type PAIRS_FETCH_SUCCEEDED = typeof PAIRS_FETCH_SUCCEEDED;

export const PAIRS_FETCH_FAILED = "PAIRS_FETCH_FAILED";
export type PAIRS_FETCH_FAILED = typeof PAIRS_FETCH_FAILED;

export const SELECT_TICKER = "SELECT_TICKER";
export type SELECT_TICKER = typeof SELECT_TICKER;

export const TICKER_FETCH_REQUESTED = "TICKER_FETCH_REQUESTED";
export type TICKER_FETCH_REQUESTED = typeof TICKER_FETCH_REQUESTED;

export const TICKER_FETCH_SUCCEEDED = "TICKER_FETCH_SUCCEEDED";
export type TICKER_FETCH_SUCCEEDED = typeof TICKER_FETCH_SUCCEEDED;

export const TICKER_FETCH_FAILED = "TICKER_FETCH_FAILED";
export type TICKER_FETCH_FAILED = typeof TICKER_FETCH_FAILED;
