export const PAIRS_FETCH_REQUESTED = "PAIRS_FETCH_REQUESTED";
export type PAIRS_FETCH_REQUESTED = typeof PAIRS_FETCH_REQUESTED;

export const PAIRS_FETCH_SUCCEEDED = "PAIRS_FETCH_SUCCEEDED";
export type PAIRS_FETCH_SUCCEEDED = typeof PAIRS_FETCH_SUCCEEDED;

export const PAIRS_FETCH_FAILED = "PAIRS_FETCH_FAILED";
export type PAIRS_FETCH_FAILED = typeof PAIRS_FETCH_FAILED;